### ISSUE TITLE
Plan tables

### ISSUE THREAD

**Issue by szabii70** [bprof-spec-codes/oetube#6]

**Comment by Beres0** [comment]
[https://viewer.diagrams.net/?tags=%7B%7D&highlight=0000ff&edit=_blank&layers=1&nav=1&title=OeTubeDesign.drawio#R7V1bk5u4Ev41U%2BV9cMqAr48eezbrczKbqbnk1D6lsFE8VDB4AU8y%2BfVHF8AgNbYwCDszqkpqbBkJXVpff91qSVfWbPPzY2hvn28DB3lXZs%2F5eWXNr0zTHJkj%2FIekvLIUY9wbsJR16DpJ2j7hwf2FksRekrpzHRQVHoyDwIvdbTFxFfg%2BWsWFNDsMgx%2FFx74FXvGtW3uNhISHle2Jqf9znfiZpY7TdpH0v5C7fk7fbAwn7JeNnT6ctCR6tp3gRy7JurmyZmEQxOzT5ucMeaT30n5h%2Bf4s%2BTWrWIj8WCZD3%2Bobt3%2F%2Fs%2Bv2rr%2F9ZUdP%2Fflw0u33WTEvtrdLWnzn2a%2BeG%2BEyp9P1OkRrO0b3pJbm0N5sr6xrD%2F90%2FRGPS5ayJilJK%2BPXtOuiH%2B7Gs3387fpb4McPyS8G%2Fm577trHn1e47ijECS8ojF3c69Pkhzgg5a6eXc%2F5ZL8GO9LCKLZX39Nv189B6P7CxdpeUib%2BOYwTATKHhSceSE6c3MOpIYrwM3dptxlc0q39s%2FDgJ5v0BE1YBZ5nbyN3mTVjY4dr178O4jjYJA%2F9eHZj9LC1V%2BSZH3hSkIrEm7SS4qAl40g6AP3MJSWD%2BBEFGxSHr%2FiR5Neu0UskKp1Tydcfe%2Fns95O055xs9lNJtJM5sc7K3osN%2FpBIThUpGghSdGXitvYWONcU%2F2XS0lsjLEUz0gGh%2B4LFisgLSRpSkVqG%2BFMiSiTz3%2FYGFzaN4tD115Vzz1G0Ct1t7Ab%2B6YUsYrSJWBMW98h2Pvve6ycyNwpzIZ0x5Gl%2BTlR84SxENqnyo0vbPscZ6EeZcnJzb%2FjvLqDJQeigsIslNwhZM17ssNPt5tP%2FoC9PcwDVCULJYeTmP5bnmM7LMPiOZqwKcz9ggOB6HpeUYoKHvsWliBDhmYUH8hN9Zt7fp9wnck6SApz3m0ex9tl1HOST2RzEdmyzqUvm6TZw%2FZjOg8E1%2Fodnxqz3YXA1mJOWDa6N%2FXf8jzwexrPAx22xXTpzEcaFH4hgQ%2FUpfxiJjwNBMu8xyEnNe2PSVzXvh8C856TAc%2BnoMilIVahxkghs8GB6aD%2Fmj0Qk5l1DkAtLlAsLkAHPXiLvLohcBhLzkD3Lycax4S%2FKt%2Bs%2Fo9CNlY67KQn4Y1XDPhKGvYu%2FpjDY%2BaMM3bInCIzMfILv5szdEApmzlZ56Mu%2BYuwpLe4BxURHdPy8oviDQVXGYsrz5jRExwG0hWRJU8chwN95wUQ1wFm%2BkL8k77GM92iDkWqfl7Q0n0vDabtwms6X43hqqppYY2FiUWlizMKa3vixG79qot0O0e4b%2FQLPtkTYNSeQfPSV8exJCc%2F%2BwvCjBtnGKEbVoO0ViTNXHpz5M2GT%2BGEylzVs1YKtsbSUlrNAUCr7qkjgoKdJYG0SWHnYR5JgpIoDDgxh1LsZEBFKU8ra9o9QFkgt0UMUL0Wm43RNQ0%2B70DMSCRMog0NVfGlgCkL4MQx2W%2B26vExG1TWMouuyD8BY3wJEyOqp4lQDq4RTNeG7pFJ1kueRcwSeXpBA504s5xZtlig87gyFZtch7ig2tJLT83RvZYnHN5ojD8WIlLEMAq%2B8W%2FFTkKNW66AaOigD9FpOUAhAjIEy%2FisuoWn%2BW5H%2FVh93YyypOZQRYHHNixBgyj%2FKyS%2F7udT9ScGr6Ao9yfvJWFC5qc%2FAvLOLqNn%2BFBEGfjwjc1jm8lKkJTBbzK0hsFUINMaA4xLEQEMZERcXgr4k7nBCxLGEaxp%2BOTTcGowKLNzsAVg6gnxIhjIWLi4pXQILb4o8z3ehvS%2BEwDqGK79yMdPVCkWEgrMPj6%2FbE0nyiREGTZNt1gyqNeoYFieRe%2FxV8%2FvWldtQGqsO8HsImoyRMn4vLsppfl%2BV31cfd1mdpIzfi2ttmYP7iHO7wO%2BdFPrhCIeTAxwYv6od3XCsGAbRHVvUPDIFYFMjh%2FGddeKcpd9k8jOLI1%2BEy5kcSXaNyu2icg8wOaDZafZUmRxDcdkxx4pIrMRuI2tQ9GpbCoBQvVHjoc9FHw8BR4wBrQJNVNkO6fJSPoY9ZYM8rNztlp67EtO156I%2BjGQzsg65A0VnqIrbDUXf7RPzien1wwvEHmH9cAzsfbDA9UNlnouhkr0PNxvb9Wq5HGr7PqZLLG23Ta9i8v4GPt%2BHDx80DNeD4SY2EoCTSN0a2lBvJKhtY1cfd2gNDRx4VTb2EN5IQFRwuYlNf6UWNqIgmVna5G3gXoLewfAyBnMdO4O7LJysklGukewCkAxaCoOhLAWYxmV6LAZGUkqpTdHm6eCEs0W7AB00wC0cyrzFYzGc7O6%2FKTgkiz7iPk3aV92IddaUsit0BW%2FLxJrSmrBPysrELWfFZg9AydQKarsOe3x1fQeLSXs1YFrm3LVIdJ6omt6ihFGd%2FBXq9rfZ3pS2fI3d99PoZzt6fi9t%2FUBJYVlb22m9UFPNUWtw1LE8azng9AQ5Sl%2BV2TURl06o%2F5tF9mmmqoCpDicnMtWxKr%2FlRLRTCFGd%2FamUrXLgQ4JIv56ZR7bfaroMnmu21gRvQRNMGln%2BgjBAmds1PchA2D%2BnVUDzKqCfugYqOyuU7X2btO2sKAHjFl51CG3fVkthP8XbbOsRg7lVrd52s4NQU4i3RiFMaa1SkUIo83dPxAgaSiGSrQqaSDRPJHhb0hic3ZYUY2Dat6roGWramNSa4E1ogiaCeFo2Jsv2gGod0LwO4Fe%2BocPpWl75nojBPHrl%2Bw2vfP%2FmQ%2BuUpOe2Sr2XJmc71N6H04DtZfsa093T76PJbvTVSXY%2Bv5MWO8n%2B7RLPUNsQelZHVRvtK0nXjqq3aZ40sY%2B%2F5aiHbBmFN1DYtR3aSGncSBlxu7UsYE9%2Fts%2B%2FHSPF6B0Ie%2Bi1CEDb5Jh%2FEBrPUiPef1bAZbbZ0V9GW8U4fT6jjh5E%2FF7oke04X%2FOnQmh1WEcd7lVLrWPbQShUqA%2BB1f%2Byy0e0Omw%2BACTjP%2BdUh8D9f2900VxHgLzFtjqH%2FHXvysq%2F7HCUt9VizZdq8iVLWnteEF%2BCDilg4kE4EShy5IduRPkOEThMFLc%2FQZGbTx%2BnOWFjBR4Wtly%2FHz1UJjvxgLKjUtkgw2%2Fv4oDVOGFsciLdiMOA3yUxgO7cGkPDbqmKbTF6p57%2FSKan44ZolZwKEWFO%2FFwcty0KsaagQzZfYq67xH15t08DRgeXQV42y6677jXU91kPZn0P0FMD6vqxspO9jB504VljU%2B7z7XTx93ufdEY2ztnAT8SBz%2B6ObmnSGaKv9rRJl%2BitC51zvRHX9xYQyzfuwbsClPW96CI9Sq24STcsm3M3fz8uHhc3DxV51dubdeNBceClb5dUB7YGdBOSzJwzjyu6BrpsbBZPre9agIIaWcBMGRkDZX0GXf7S0Fy5v7n7%2FLB4%2FHyv54tpmPxRLyawfQo8glbhhIGO%2Fmto8B9u7r8sZnrg97edZwMPrCKCZzwpHHjREkw95%2FdoS86BC%2FBrrOn%2By7UdEYeQcIroLHdJuD5QtHWfvGFyVg%2BghS0IVEbqZEtfN1D7KMT9BK11BiZ4BY6ypRhTNHloeEpVREkP1Ndwcn44gZb4WsYTE7LmNJ5Uw5Nsbv5OeGIKA08OoqwKJ%2BzwSo0mF4AmJuAcahtNTvURaDQBZubvhCYl%2B7yrwkl6wajGk%2FPjiQWd%2F90ynkAuFI0nFfGkkRP%2F28UTS7R2FuTw9geMHvQM9zx2PM7IbMRiwDMRazoPNviHBxS%2BuCvxdkaNJEqQxOzxa4aAQA3AJUNlZ1AYlmjokMsEvtI7AfYCxK4ZvfaCpShUh4VNiG3aF%2F8Y2n60Chxa%2FoJLKXHV6lghOXSzmrC9QGFUiG6i7aXVWlW1Vn3gRyKfAQdeWYiYBZlH1wRwmG4LA%2Fynw0EGu8lSDJwk%2BT6imGadRq%2F%2BSrj88tGOvhfB60%2FXQ%2Fco2nnCggJc%2FoP9gqAXsOtUsCSSdaoFuYYzJtVH9oagIx64Yg3K6v4UevlKayRsGQlH4nUosFpWdk2nYZ26ntFOVME%2Beu1QWAEY96YwrMCC4t5kOq1%2FvNMuJ%2F7Jsvi%2BH0JnorYcc9gvD%2BmoH3M4vbv7tJhNHxef333gYX8w5kffFEd%2FqCzaFy3vF9%2F%2BcV4%2B2cNf7mry7%2Br7%2BGNXtCHoclqR39NvLm75HG2Rj7XH6lUYNW15luk5QUIAOSq3PIdcOAh0hx2s4ppADFBmRK6vr36rJwPlU%2FMibD6wenph5JjF1%2Fygt2jvgbWDmMI1pzA6GAzguyRxL5Iu6bj%2BloD6NL1jd4YxnkshlQ%2FXuw3urKikMLIH79Z6GjMrjRV6Z5Nu4QvmU48XPvVt7%2FUXoi3r0HMicP7la4wiEpZIX8g%2B0JswrSk7VsX%2FFpRXFS3I3kxqekaSPbAKdkRWpi6xPjW8tgqv0oak0YAhCdZPXCji%2FayamZ2XmfEbyKTXBAaqmJkYpquZmQLoGFw2MxPPpdXMrD4zOzzo52ZmkNPxmlMYLTGzhDzRlzPX%2F2HyRB9k5EkDVZtAJctxRqoojuj0pURah0T8DvSnNyjSHzM9WumYOJkTVfIEbKKmIQvUglMXEfEieEx5HyqcjyxGkNssfOc%2FwfLW9rHMZ5WDftLw2DA8Ti6bx4H70jWRq0vkDo%2B6LJFTtyIjutdZeAEJdUhUY4dDNHPGY5A5g9AFJmxXLCyCghYNi8AJhciII2ERR2Ii2PNgvAVWboG3Y%2FLB3FxZaTk4ZneISwR34JfdZyVGQAiJWPan%2FFZUmuL6YiiJ3Lv3Hj6pV1cNXQHciMXeLPgLjw4LWFBpnM1C7KgD9a%2FaXzNSc6EWbCRgeQV6m559l7X%2B6misDpNLLmJnb%2BlIVLt63oTf4nGUEpH940d2EGgqoJQKGMAW%2FJJFV2XcVvTqFFgmHheM81iKqGAV%2BCNHbvcZpuE64gVrpn3KF7Ta3wdis2DBGyrjI6JrSdrqkRc7jWcNr26NLty2OTXgT9s2NYb93F5q4MgHPoCA6bEOhy6w4XLzE612KZUSAIb4qaM9r9II0yrCyDqXx6oIE3AOBLuoebtNXcXWdBbunFxCcQMv27lLLCv6EQ8y2c%2BbHGOE6b%2FDrB%2BaLmQkl%2Bzkf0npFbPicgU%2BbZ1CwqXuFO733i7vsoQzQYeSSNnIVmFYfkU%2FEOVda2EXOr8vHfY203yFLafJ0hu43AJuWwfL3fFnbHCHbsC58H%2BSkavPVbZxCKiSxMEcGtRrgvqR7TXS1khP2azQYacqeOORcYeOdWqXOIKRp5w%2B73DQWBru8LT1Atsp2QaYRixU9nYr3bo4dZxbtFmiMHFrMzQn9aUw6uAOn4ouWvZbsfhjzlHS7BdU8rINTW7ydaQU8GX73stxreL7WL4SpqVVQ6uqIbuH4qhuSBG7eZ%2BCqBvYmpYs409OEiSMn36UZvzZtZrljD9XIGP8%2BwTN%2BC%2BA8Uv7RrLzeZuXX1HJ7T2tBYrNn5N5IC5lT67LY6u%2BcKvJEqxftEJSMzlfLY3BDftcrEboubKdgeAB4Zqd1%2FbqHh52AzjEuVV2DhwPnrp1c%2BychzFzVkrQr8gKv4dW5SEVhKgXF%2Fylwx2UBGdgfj5drVAUUQyMWGMXxfiMhNnC3Jk9VoU5498YVz%2F8YvpW58TXagBvFcCzw0PO5zUXETw9sV%2BaRu%2BP%2BCdSn36TJtNphsN8ulgso9SFNM2q22fVfUM44uLsrNoUlVMtVp1eZC%2FtSr%2FLZ6jGstN38UQbuHxDQ3XDUG0e3jxzdq5t6m1%2BSjzhh4f97FzbBHf65TChnHEfotvHXeIfEoc4C0MnTnEZ1q3yLD%2FMuQlHSPzGGS4XSbdLngCpL4b7AIEkQ5p5k9wH356wcc29Lx%2FQL4B7izFxZM1bmnezBXIiduSTNN8mDx%2Fm2vviGM%2FOvmuOfQEc20y9bueLVQEON0%2BjPOQcxeX%2Baz5rNZIuQ5xLo1qkGf5T%2BnApu9dY3jCWH96vcXZyDpzNrsl5A%2BT8yDadc5Nz8Bj060QhnxCognMS2kgxT24%2F46mr1DJ8m1QlBVCoNiCpr%2BHpk60TIykOc4A3Ua9DAbyylbqc2lSJdioad0dsIBn7Tiu%2BVhWftBGT3djQPAbqKBxty0jaMsZgxG14xJTs7CsGlo7D0Sh8EIWtC4%2FDsXQcjgrz48iwn9%2F8AONwrhoOptGhLhojm5gs53a3W9ACKhM%2BPCx%2BQRxK7j0Zll178nBz%2F2Uxu3lICyQHXtIyf787T%2Bo5q3u9Ir%2FrQsrRslpVjsovaKrXZRP%2BXOl2L2iC%2Bww6rqGhuTJ%2F%2FBy993kyGJj8PAHuPjegu4FOmCf4axiQMch%2B%2B4iB%2F%2Fk2cBB54v8%3D](url)
![OeTubeDesign drawio](https://github.com/bprof-spec-codes/oetube/assets/57649310/e30bfbca-8a72-4f53-a8eb-93118c6777dc)
