### ISSUE TITLE
Create models

### ISSUE THREAD

**Issue by szabii70** [bprof-spec-codes/oetube#8]
- [ ] Video
- [ ] PlayList
- [ ] PlayListItem
- [ ] User
- [ ] Group
- [ ] GroupMember
- [ ] GroupAccessibility

**Comment by mabphun** [comment]
Sziasztok!
Elkészültek a modellek:
- AccessGroup
- Group
- Member
- Playlist
- Video
- VideoItem

Üdv,
Ákos
